-- Setup JDTLS for Java files
-- vim.api.nvim_create_autocmd('FileType', {
--   group = vim.api.nvim_create_augroup('jdtls_lsp', { clear = true }),
--   pattern = 'java',
--   callback = require('lsp.jdtls').setup_jdtls,
-- })
